allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  cpu-features: set this to true or false
  prisma: set this to true or false
  ssh2: set this to true or false
  unrs-resolver: set this to true or false
